### ISSUE TITLE
Краш в мультиплеере

### ISSUE THREAD

**Issue by ANTEVETY** [Deema35/Climbing-Movement-Component#1]
Здравствуй. Классный плагин! Столкнулся с проблемой, при запуске с несколькими игроками(в том числе и в режиме дедикейтед сервера), движок (4.18.2) крашится. Тестировался ли плагин в этом режиме и планируются ли обновления?

**Comment by Deema35** [comment]
Здравствуйте.

Нет мультиплеер не тестировался. И поскольку я не занимаюсь многопользовательскими играми, обновления с решением данной проблемы не выйдет.
